import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/layouts/layouts/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          text-gray-900 dark:text-gray-100
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen w-full overflow-hidden">
            {/* Sidebar - Fixed on the left */}
            {/* <Sidebar /> */}
            
            {/* Main content area - Takes remaining width */}
            <div className="flex flex-col flex-1 h-full overflow-auto">
              {/* Navbar - Fixed at the top of the content area */}
              <Navbar />
              
              {/* Page content - Scrollable */}
              <main className="flex-1 p-4 overflow-auto bg-white dark:bg-gray-950">
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
